DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS word_en_tr;
DROP TABLE IF EXISTS word_en;
DROP TABLE IF EXISTS word_tr;
DROP TABLE IF EXISTS sentence_en_tr;
DROP TABLE IF EXISTS sentence_en;
DROP TABLE IF EXISTS sentence_tr;
DROP TABLE IF EXISTS comment;

CREATE TABLE "user"(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created DATE
);

CREATE TABLE word_en(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(50),
    img VARCHAR(100),
    def VARCHAR(250)
);

CREATE TABLE word_tr(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(50),
    img VARCHAR(100),
    def VARCHAR(250)
);

CREATE TABLE word_en_tr(
    word_en_id INT,
    word_tr_id INT,
    FOREIGN KEY (word_en_id) REFERENCES word_en("id"),
    FOREIGN KEY (word_tr_id) REFERENCES word_tr("id")
);

CREATE TABLE sentence_en(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(250),
    img VARCHAR(100),
    quotes VARCHAR(50)
);

CREATE TABLE sentence_tr(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" VARCHAR(250),
    img VARCHAR(100),
    quotes VARCHAR(50)
);

CREATE TABLE sentence_en_tr(
    sentence_en_id INT,
    sentence_tr_id INT,
    FOREIGN KEY (sentence_en_id) REFERENCES sentence_en (id),
    FOREIGN KEY (sentence_tr_id) REFERENCES sentence_tr (id)
);

CREATE TABLE comment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment VARCHAR(250),
    phrase_id INT NOT NULL,
    type VARCHAR(50),
    lang VARCHAR(50),
    created Date
);

-- IF NOT EXISTS(SELECT * from "user" where username='')
-- THEN
INSERT INTO "user"(fullname, username, email)
VALUES ('ibrahim AKIN', 'ibrahimakin', 'ibrahim-akin@msn.com'),
       ('ibrahim', 'ibrahim', 'iibrahimakinn@gmail.com'),
       ('AKIN', 'akin', 'ibrahimakin.mail@gmail.com');

INSERT INTO word_en("value",img,def) VALUES ('Brass',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('January',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('February',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('March',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('April',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('May',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('June',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('July',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('August',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('September',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('October',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('November',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('December',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Monday',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Tuesday',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Wednesday',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Thursday',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Friday',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Saturday',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Sunday',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Aisle','/projects/english-learner/source/img/aisle.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Nephew',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Neiece',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Draft',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Skulking',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to frighten',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to toss',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Lung',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Lettuce, Iceberg','/projects/english-learner/source/img/lettuceiceberg.gif',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Peach','/projects/english-learner/source/img/peach.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Apricot','/projects/english-learner/source/img/apricot.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Pomegranate','/projects/english-learner/source/img/pomegranate.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('to worship',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to wipe out',NULL,'an instance of complete destruction.');
INSERT INTO word_en("value",img,def) VALUES ('to cure',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Honey Badger / Ratel','/projects/english-learner/source/img/ratel.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Walnut','/projects/english-learner/source/img/walnut.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Subconscious',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Colossal',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Tedious',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Obnoxious',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Stringing',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Ravenous',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Appetite',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to dedicate',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to influence',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to defect',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to hesitate',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to consist of',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to call off',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to wither up / to fade',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to preserve',NULL,'maintain (something) in its original or existing state.');
INSERT INTO word_en("value",img,def) VALUES ('Zealously',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Peasant',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Pleasant',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Temptation',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Flawed',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Inevitable',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Devotion',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Apart',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Fascination',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Revelation',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Ranch',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Salvation',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Desperate',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Nonetheless',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Nevertheless',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to resurrect',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to rejoice',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Lucked out',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('For good',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Menial',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Purchasing Power',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Ice Cap','/projects/english-learner/source/img/ice_cap.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('to loosen',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Flimflam',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Manner',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Underneath',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Artifact',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Pursuit',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Incantation',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Cashpoint','/projects/english-learner/source/img/cashpoint.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Pharmacy','/projects/english-learner/source/img/pharmacy.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Chickpea','/projects/english-learner/source/img/chickpea.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Stray',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('though',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Flea market',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Thrift store',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('make a profit',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('compatible',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('complain',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to recap',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to revise',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to discuss',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('comprehend',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Cheerio',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('persuade',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('chores',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('intuition',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('cumbersome',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('dispute',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('brick-and-mortar store',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('delight',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('anticlimactic',NULL,'causing disappointment at the end of an exciting or impressive series of events.');
INSERT INTO word_en("value",img,def) VALUES ('helm','/projects/english-learner/source/img/helm.jpeg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('inconvenience',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('knackered',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('parking lot',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('own up to',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('ring a bell',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to dishearten',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('to shrug off',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('all of a sudden',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Toddler',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Dough',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('shattered',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Cinnamon','/projects/english-learner/source/img/cinnamon.jpg',NULL);
INSERT INTO word_en("value",img,def) VALUES ('Good deed',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('Attitude',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('hesitant',NULL,NULL);
INSERT INTO word_en("value",img,def) VALUES ('ferocity',NULL,NULL);

INSERT INTO word_tr("value",img,def) VALUES ('Prinçten Yapılmış',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Ocak   (1)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Şubat   (2)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Mart   (3)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Nisan   (4)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Mayıs   (5)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Haziran   (6)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Temmuz   (7)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Ağustos   (8)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Eylül   (9)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Ekim   (10)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Kasım   (11)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Aralık   (12)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Pazartesi   (1)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Salı   (2)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Çarşamba   (3)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Perşembe   (4)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Cuma   (5)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Cumartesi   (6)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Pazar   (7)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Koridor','/projects/english-learner/source/img/aisle.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Yeğen (Erkek)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Yeğen (Kız)',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Taslak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Sinsi / Korkak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Korkutmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Atmak / Fırlatmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Akciğer / Ciğer',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Marul  (Göbek Marul)','/projects/english-learner/source/img/lettuceiceberg.gif',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Şeftali','/projects/english-learner/source/img/peach.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Kayısı','/projects/english-learner/source/img/apricot.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Nar','/projects/english-learner/source/img/pomegranate.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Tapmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Silip yoketmek',NULL,'an instance of complete destruction.');
INSERT INTO word_tr("value",img,def) VALUES ('İyileştirmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Bal Porsuğu','/projects/english-learner/source/img/ratel.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Ceviz','/projects/english-learner/source/img/walnut.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Bilinçaltı',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Devasa',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Sıkıcı',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('İğrenç',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('İp çekmek / Kandırmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Son derece aç',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('İştah',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Adamak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Etkilemek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Döneklik etmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Tereddüt etmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Meydana gelmek / Oluşmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('İptal etmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Solmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Korumak',NULL,'maintain (something) in its original or existing state.');
INSERT INTO word_tr("value",img,def) VALUES ('Şevkle',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Köylü',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Güzel / Hoş',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Kışkırtma / Ayartma',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Kusurlu',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Kaçınılmaz',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Özveri',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Ayrı',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Büyüleyici',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Vahiy, İlham',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Çiftlik',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Kurtuluş',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Umutsuz',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Her şeye rağmen',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Yine de',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Diriltmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Sevinmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Şans eseri',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Temelli olarak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Vasıf gerektirmeyen',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Alım Gücü',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Buz Örtüsü','/projects/english-learner/source/img/ice_cap.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Gevşetmek / Çözmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Boş lâf / Dolandırmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Tavır',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Altında',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Eser',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Kovalama / Uğraşı',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Büyü',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('ATM (Automatic Teller Machine)','/projects/english-learner/source/img/cashpoint.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Eczane','/projects/english-learner/source/img/pharmacy.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Nohut','/projects/english-learner/source/img/chickpea.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Başıboş',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('yine de, rağmen',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Bit pazarı',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('İkinci el mağazası',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('kar yapmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('uyumlu',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('şikayet etmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('özetlemek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('revize etmek / gözden geçirmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('tartışmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('anlamak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Görüşürüz',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('ikna etmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('ev işleri',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('sezgi',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('kullanışsız, elverişsiz',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('anlaşmazlık, tartışma',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('fiziksel mağaza',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('zevk / sevinç',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('hayal kırıklığı',NULL,'causing disappointment at the end of an exciting or impressive series of events.');
INSERT INTO word_tr("value",img,def) VALUES ('dümen','/projects/english-learner/source/img/helm.jpeg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('rahatsızlık',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('çok yorgun',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('park yeri',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('kabul etmek, üstlenmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('bir şey çağrıştırmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('cesaretini kırmak',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('omuz silkmek',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('birdenbire',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Yürümeye başlayan çocuk',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Hamur',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('paramparça',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Tarçın','/projects/english-learner/source/img/cinnamon.jpg',NULL);
INSERT INTO word_tr("value",img,def) VALUES ('İyilik, iyi işler',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('Tavır / Davranış',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('tereddütlü',NULL,NULL);
INSERT INTO word_tr("value",img,def) VALUES ('gaddarlık',NULL,NULL);

INSERT INTO word_en_tr(word_en_id,word_tr_id)
VALUES (1,1),
       (2,2),
       (3,3),
       (4,4),
       (5,5),
       (6,6),
       (7,7),
       (8,8),
       (9,9),
       (10,10),
       (11,11),
       (12,12),
       (13,13),
       (14,14),
       (15,15),
       (16,16),
       (17,17),
       (18,18),
       (19,19),
       (20,20),
       (21,21),
       (22,22),
       (23,23),
       (24,24),
       (25,25),
       (26,26),
       (27,27),
       (28,28),
       (29,29),
       (30,30),
       (31,31),
        (32,32),
        (33,33),
        (34,34),
        (35,35),
        (36,36),
        (37,37),
        (38,38),
        (39,39),
        (40,40),
        (41,41),
        (42,42),
        (43,43),
        (44,44),
        (45,45),
        (46,46),
        (47,47),
        (48,48),
        (49,49),
        (50,50),
        (51,51),
        (52,52),
        (53,53),
        (54,54),
        (55,55),
        (56,56),
        (57,57),
        (58,58),
        (59,59),
        (60,60),
        (61,61),
        (62,62),
        (63,63),
        (64,64),
        (65,65),
        (66,66),
        (67,67),
        (68,68),
        (69,69),
        (70,70),
        (71,71),
        (72,72),
        (73,73),
        (74,74),
        (75,75),
        (76,76),
        (77,77),
        (78,78),
        (79,79),
        (80,80),
        (81,81),
        (82,82),
        (83,83),
        (84,84),
        (85,85),
        (86,86),
        (87,87),
        (88,88),
        (89,89),
        (90,90),
        (91,91),
        (92,92),
        (93,93),
        (94,94),
        (95,95),
        (96,96),
        (97,97),
        (98,98),
        (99,99),
        (100,100),
        (101,101),
        (102,102),
        (103,103),
        (104,104),
        (105,105),
        (106,106),
        (107,107),
        (108,108),
        (109,109),
        (110,110),
        (111,111),
        (112,112),
        (113,113),
        (114,114),
        (115,115),
        (116,116),
        (117,117),
        (118,118),
        (119,119),
        (120,120),
        (121,121);

INSERT INTO sentence_en("value",img,quotes) VALUES ('This is the village in which my father was born.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Whom do we pay?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Nobody knows where she came from.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('It is the city of which I told you.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('We know whose it is.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I know where I am.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('The man, whose son is here, is in the house as well.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('The child who is not born.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I have a friend whose father is a teacher.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('What was she thinking of doing?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I saw him running.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('The children entered running.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('You are getting big. / You are growing.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('She is afraid of having to leave.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I am getting tired.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Are you having a baby?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Any bed is better than not having a bed.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('He is talking of going to Spain this winter.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Feed on them.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('You wrote what you were told.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('A doctor found him and cured him.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('How did I not think of that.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Different strokes for different folks.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I should have told the truth.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Lost track of time.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Please don''t make things up.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I am stuffed.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I object.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Have you ever made a snowman?','/projects/english-learner/source/img/snowman.gif',NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I''m under a lot of pressure.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Dig in!',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Take your share.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Can I have a second serving?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Let''s go on a spending spree.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('These are rip-offs.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('The food is going to get cold.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('The manager came up with a new way for us to increase the sales.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I wonder what Liz has up his sleeve for my birthday celebration.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Do you have anything up your sleeve that can solve our problem?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I''m up to my eyeballs in work right now!',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('He is very afraid of dogs.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('You''re making me blush.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Thanks for inviting me, but can I take a rain check?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I''d like to book a room from July 23rd through 25th.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Have the courage to follow your heart and intuition.',NULL,'Steve Jobs');
INSERT INTO sentence_en("value",img,quotes) VALUES ('Don''t beat yourself up!',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I''m quite delighted.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Fill me in.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('It''s unusual, isn''t it?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I couldn''t get comfortable.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I''m sick of this.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('They have him at the helm.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('We apologize for any inconvenience.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('One came off.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I''m through with nursing.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I am knackered.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('We could have had it all.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Go easy on me.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I was on the edge of my seat.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I wanted extra gravy on my mashed potatoes.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Mr. Reynolds is on the warpath this morning.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Somebody scratched his car in the parking lot.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('He might even forgive them if they own up to it.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Do you fancy having a drink in the hotel lounge?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('How long does it take by bus?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Go straight ahead.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Hit me up anytime you are in the area.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('She''s pretty gutted about this marriage.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('It''s very disheartening.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Where did the sun go all of a sudden?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Where did the sun go all of a sudden?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I can already feel some spots of rain.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I am having a hard time getting up in the morning.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('The best is yet to come.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('It''s pretty strange that we keep running into each other.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I feel like lying around all day.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Which bus goes to the train station?',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('It is important that she travels more.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I''m going to heat up my pan.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I need to preheat the oven.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Just add some seasoning!',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Great minds discuss ideas; average minds discuss events; small minds discuss people.',NULL,'Eleanor Roosevelt');
INSERT INTO sentence_en("value",img,quotes) VALUES ('I have a lot on my mind.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Peace at home, peace in the world.',NULL,'Mustafa Kemal Atatürk');
INSERT INTO sentence_en("value",img,quotes) VALUES ('You shouldn''t have!',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Yesterday when we spoke on the phone, I was at my aunt''s house.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('It''s dusk.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('I have had a hat since you have had a hat.','/projects/english-learner/source/img/hat.gif',NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('Everyone is in favor of your idea.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('We do not know what attitude to take.',NULL,NULL);
INSERT INTO sentence_en("value",img,quotes) VALUES ('That crisis turned out to be a big opportunity.',NULL,NULL);

INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bu benim babamın doğduğu köy.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Biz kime öderiz?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Kimse onun nereden geldiğini bilmiyor.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('O sana bahsettiğim şehir.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Biz onun kimin olduğunu biliyoruz.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Ben nerede olduğumu biliyorum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Oğlu burada olan adam da evde.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Doğmamış çocuk.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Babası öğretmen olan bir arkadaşım var.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('O ne yapmayı düşünüyordu?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Onu koşarken gördüm.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Çocuklar koşarak girdiler.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Sen büyüyorsun.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Gitmek zorunda olmaktan korkuyor.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Ben yoruluyorum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Sizin bir bebeğiniz mi oluyor?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Herhangi bir yatak, bir yatağa sahip olmamaktan daha iyidir.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bu kış İspanya''ya gitmekten bahsediyor.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Onlarla beslen.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Sana söyleneni yazdın.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bir doktor onu buldu ve iyileştirdi.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bunu nasıl düşünemedim.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Zevkler ve renkler meselesi.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Doğruyu söylemeliydim.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Zamanın nasıl geçtiğini anlayamamak.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Lütfen bir şeyler uydurma.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Tıka basa doydum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('İtiraz ediyorum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Hiç kardan adam yaptın mı?','/projects/english-learner/source/img/snowman.gif',NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Çok baskı altındayım.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Gömül! (yemeğe)',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Payına düşeni al.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('İkinci bir tabak alabilir miyim?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Hadi bir harcama çılgınlığı yapalım.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Çok kazıklar.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Yemek soğuyacak.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Yönetici, satışları artırmamız için yeni bir yol buldu.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Doğum günü kutlamam için Liz''in ne planı var merak ediyorum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Elinde sorunumuzu çözebilecek herhangi bir planın var mı?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Şu an işimin başındayım!',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('O köpeklerden çok korkar.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Beni utandırıyorsun.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Davet ettiğin için teşekkürler, ama başka sefere gelsem olur mu?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('23''ünden 25 Temmuz''a bir oda rezervasyonu yaptırmak istiyorum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Kalbinizi ve önsezilerinizi dinleyecek cesaretiniz olsun.',NULL,'Steve Jobs');
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Kendine bu kadar yüklenme!',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Ben oldukça sevinçliyim.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bana anlat.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bu alışılmadık, değil mi?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Rahat edemedim.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bundan bıktım.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Dümende o var.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Verdiğimiz rahatsızlıktan dolayı özür dileriz.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Biri çıktı.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Hemşirelikten vazgeçtim.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Pestilim çıktı.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Her şeye sahip olabilirdik.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bana yüklenme.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Koltuğumun ucundaydım.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Patates püresinin üzerine fazladan sos istedim.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bay Reynolds bu sabah burnundan soluyor.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Biri otoparkta arabasını çizmiş.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Hatta eğer yaptığını kabul ederlerse onları affedebilir.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Otel lobisinde bir şeyler içmek ister misiniz?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Otobüsle ne kadar sürer?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Dümdüz git.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Buralarda olduğun zaman bana haber ver.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bu evlilik konusunda canı oldukça sıkkın.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Bu çok moral bozucu.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Güneş bir anda nereye gitti?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Güneş bir anda nereye gitti?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Şimdiden bazı yağmur damlalarını hissedebiliyorum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Sabahları uyanmakta zorlanıyorum.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('En iyisi henüz gelmedi.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Birbirimizle karşılaşmaya devam etmemiz oldukça garip.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Canım bütün gün uzanmak istiyor.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Hangi otobüs tren istasyonuna gider?',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Onun daha fazla seyahat etmesi önemli.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Tavamı ısıtacağım.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Fırını önceden ısıtmam gerekiyor.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Sadece biraz çeşni ekle!',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Büyük beyinler fikirleri; ortalama beyinler olayları; küçük beyinler insanları tartışır.',NULL,'Eleanor Roosevelt');
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Aklımda çok şey var.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Yurtta sulh cihanda sulh.',NULL,'Mustafa Kemal Atatürk');
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Zahmet etmeseydin!',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Dün biz telefonda konuştuğumuzda, ben teyzemin evindeydim.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Hava kararıyor. (Alacakaranlık)',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Senin bir şapkan olduğundan beri benim bir şapkam var.','/projects/english-learner/source/img/hat.gif',NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Herkes senin fikrin lehinde.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('Biz hangi tavrı almamız gerektiğini bilmiyoruz.',NULL,NULL);
INSERT INTO sentence_tr("value",img,quotes) VALUES ('O krizin büyük bir fırsat olduğu ortaya çıktı.',NULL,NULL);

INSERT INTO sentence_en_tr(sentence_en_id,sentence_tr_id)
VALUES (1,1),
	(2,2),
	(3,3),
	(4,4),
	(5,5),
	(6,6),
	(7,7),
	(8,8),
	(9,9),
	(10,10),
	(11,11),
	(12,12),
	(13,13),
	(14,14),
	(15,15),
	(16,16),
	(17,17),
	(18,18),
	(19,19),
    (20,20),
	(21,21),
	(22,22),
	(23,23),
	(24,24),
	(25,25),
	(26,26),
	(27,27),
	(28,28),
	(29,29),
	(30,30),
	(31,31),
	(32,32),
	(33,33),
	(34,34),
	(35,35),
	(36,36),
	(37,37),
	(38,38),
	(39,39),
	(40,40),
	(41,41),
	(42,42),
	(43,43),
	(44,44),
	(45,45),
	(46,46),
	(47,47),
	(48,48),
	(49,49),
	(50,50),
	(51,51),
	(52,52),
	(53,53),
	(54,54),
	(55,55),
	(56,56),
	(57,57),
	(58,58),
	(59,59),
	(60,60),
	(61,61),
	(62,62),
	(63,63),
	(64,64),
	(65,65),
	(66,66),
	(67,67),
	(68,68),
	(69,69),
	(70,70),
	(71,71),
	(72,72),
	(73,73),
	(74,74),
	(75,75),
	(76,76),
	(77,77),
	(78,78),
	(79,79),
	(80,80),
	(81,81),
	(82,82),
	(83,83),
	(84,84),
	(85,85),
	(86,86),
	(87,87),
	(88,88),
	(89,89),
	(90,90),
	(91,91);

INSERT INTO comment (comment, phrase_id, type, lang)
VALUES (':)', 1, 'word', 'en'),
       (':D', 1, 'sentence', 'tr');